server:
  port: 6543
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  application:
    name: maat-server
  data:
    mongodb:
      uri: mongodb://mongodb.clsaa.com:27017/maat

#spring.jackson.serialization.WRITE_DATE_KEYS_AS_TIMESTAMPS: true  #返回JSON统一日期为时间戳
#spring.jackson.serialization.WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS: false
#spring.jackson.time-zone: GMT+8

maat:
  retryWaitSeconds: 10,20,30,40,50,60             #每隔10s,20s,30s,40s,50s重新发送一次,60s时标记为已死亡
  mq:
    name: RocketMQ                                #启用的MQ名称
    RocketMQ:                                     #RocketMQ相关配置
      namesrvAddr: maat.clsaa.com:9876              #name-server地址与端口,多个可用分号隔开
      groupName:  MAAT_TRASACTION_PRODUCER_GROUP  #生产者组名称
      instanceName: MAAT_TRASACTION_INSTANCE      #要发送到的MQ集群
      maxMessageSize: 131072 # 1024*128           #最大消息长度
      sendMessageTimeout: 10000                   #消息发送超时时间